In [7]:
import pandas as pd
import toad
data = pd.read_csv('data/germancredit.csv')
data.replace({'good':0,'bad':1},inplace=True)
data.shape

(1000, 21)

In [8]:
data['creditability'] = data['creditability'].astype(int)

selected_data, drop_list = toad.selection.select(data,target='creditability',empty=0.5,iv=0.05,corr=0.7,return_drop=True)

In [9]:
drop_list

{'empty': array([], dtype=float64),
 'iv': <StringArray>
 [     'installment.rate.in.percentage.of.disposable.income',
                                   'personal.status.and.sex',
                               'other.debtors.or.guarantors',
                                   'present.residence.since',
                   'number.of.existing.credits.at.this.bank',
                                                       'job',
  'number.of.people.being.liable.to.provide.maintenance.for',
                                                 'telephone',
                                            'foreign.worker']
 Length: 9, dtype: str,
 'corr': <StringArray>
 []
 Length: 0, dtype: str}

In [10]:
from boruta import BorutaPy
import joblib
from sklearn.ensemble import RandomForestClassifier

In [11]:
pd_data = joblib.load('data/train_woe.pkl')

E:\anaconda\envs\heima\Lib\pickle.py:1632: VisibleDeprecationWarning: dtype(): align should be passed as Python or NumPy boolean but got `align=0`. Did you mean to pass a tuple to create a subarray type? (Deprecated NumPy 2.4)
  stack[-1] = func(*args)

ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'

In [12]:
pd_data = joblib.load('data/train_woe.pkl')

E:\anaconda\envs\heima\Lib\pickle.py:1632: VisibleDeprecationWarning: dtype(): align should be passed as Python or NumPy boolean but got `align=0`. Did you mean to pass a tuple to create a subarray type? (Deprecated NumPy 2.4)
  stack[-1] = func(*args)

ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'

In [13]:
print(pd.__version__)

3.0.0

In [14]:
import pickle
pd_data = pd.read_pickle('data/train_woe.pkl')

E:\anaconda\envs\heima\Lib\site-packages\pandas\compat\pickle_compat.py:80: VisibleDeprecationWarning: dtype(): align should be passed as Python or NumPy boolean but got `align=0`. Did you mean to pass a tuple to create a subarray type? (Deprecated NumPy 2.4)
  stack[-1] = func(*args)
E:\anaconda\envs\heima\Lib\site-packages\pandas\compat\pickle_compat.py:80: VisibleDeprecationWarning: dtype(): align should be passed as Python or NumPy boolean but got `align=0`. Did you mean to pass a tuple to create a subarray type? (Deprecated NumPy 2.4)
  stack[-1] = func(*args)

In [15]:
pd_data.shape

(215257, 79)

In [16]:
pd_data.head()

,SK_ID_CURR,TARGET,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,REGION_RATING_CLIENT_W_CITY,REG_CITY_NOT_LIVE_CITY,...,p_NAME_SELLER_INDUSTRY_Connectivity,p_NAME_YIELD_GROUP_XNA,p_NAME_YIELD_GROUP_high,p_NAME_YIELD_GROUP_low_action,p_NAME_YIELD_GROUP_low_normal,p_PRODUCT_COMBINATION_Card Street,p_PRODUCT_COMBINATION_Cash Street: high,p_PRODUCT_COMBINATION_Cash X-Sell: high,p_PRODUCT_COMBINATION_Cash X-Sell: low,p_PRODUCT_COMBINATION_POS industry with interest
125406,245429,0,0.610118,0.016406,0.301190,0.092078,-0.099822,0.275679,-0.020586,-0.048048,...,0.053257,0.383810,0.065650,0.073290,0.164891,-0.063697,-0.028915,-0.033661,0.083527,-0.065841
8155,109510,0,-0.366495,-0.410334,-0.440745,-0.608958,0.164707,0.193847,-0.536494,-0.048048,...,-0.065479,-0.090837,-0.132787,0.073290,-0.241145,-0.063697,-0.028915,-0.033661,0.083527,-0.348529
154053,278546,0,0.038650,0.016406,0.301190,0.371651,0.075169,0.060654,-0.020586,-0.048048,...,-0.065479,-0.090837,-0.132787,-0.316556,-0.241145,-0.063697,-0.028915,-0.033661,0.083527,-0.348529
300963,448668,0,-0.366495,-0.158446,0.301190,-0.171601,0.075169,-0.057870,-0.020586,-0.048048,...,-0.065479,-0.090837,-0.132787,-0.316556,0.164891,-0.063697,-0.028915,-0.033661,0.083527,-0.348529
269546,412373,0,-0.366495,-0.410334,-0.051704,-0.171601,-0.099822,-0.297834,-0.536494,-0.048048,...,0.053257,-0.090837,0.110022,-0.152116,0.164891,-0.063697,-0.028915,-0.033661,-0.239387,0.084509

In [17]:
pd_x = pd_data.drop(['SK_ID_CURR', 'TARGET'], axis=1)
x = pd_x.values
y = pd_data['TARGET'].values

In [18]:
rf = RandomForestClassifier(n_jobs=-1, class_weight='balanced', max_depth=5)
feat_selector = BorutaPy(rf, n_estimators='auto', random_state=1, max_iter=3)
feat_selector.fit(x, y)
"""
from sklearn.ensemble import GradientBoostingClassifier

# 使用 GradientBoosting 或 LightGBM 更快
rf = GradientBoostingClassifier(
    n_estimators=50,
    max_depth=3,
    random_state=1,
    verbose=1
)

feat_selector = BorutaPy(
    rf,
    n_estimators='auto',
    random_state=1,
    max_iter=5,      # 减少迭代
    verbose=2       # 显示进度
)

feat_selector.fit(x, y)

"""

BorutaPy(estimator=RandomForestClassifier(class_weight='balanced', max_depth=5,
                                          n_estimators=248, n_jobs=-1,
                                          random_state=RandomState(MT19937) at 0x1717CB0A440),
         max_iter=3, n_estimators='auto',
         random_state=RandomState(MT19937) at 0x1717CB0A440)

In [19]:
feat_selector.support_

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [20]:
feat_selector.ranking_

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
pd_x.columns[feat_selector.support_]

Index([], dtype='object')

In [22]:
pd_feature_select = pd.DataFrame({'feature_name':pd_x.columns,'choose or':feat_selector.support_})
pd_feature_select[pd_feature_select['choose or']==False]

                                        feature_name  choose or
0                                    AMT_GOODS_PRICE      False
1                         REGION_POPULATION_RELATIVE      False
2                                         DAYS_BIRTH      False
3                                      DAYS_EMPLOYED      False
4                                  DAYS_REGISTRATION      False
..                                               ...        ...
72                 p_PRODUCT_COMBINATION_Card Street      False
73           p_PRODUCT_COMBINATION_Cash Street: high      False
74           p_PRODUCT_COMBINATION_Cash X-Sell: high      False
75            p_PRODUCT_COMBINATION_Cash X-Sell: low      False
76  p_PRODUCT_COMBINATION_POS industry with interest      False

[77 rows x 2 columns]

In [23]:
from pandas import DataFrame
import numpy as np
from statsmodels.stats.outliers_influence import variance_inflation_factor
def check_vif(df:DataFrame):
    lst_col = df.columns
    X = np.matrix(df)
    VIF_list = [variance_inflation_factor(X,i) for i in range(X.shape[1])]
    VIF = pd.DataFrame({'feature name':lst_col,'VIF':VIF_list})
    return VIF

In [25]:
from sklearn.svm import LinearSVC
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import RFE

In [27]:
X,y = load_iris(return_X_y=True)
lscv = LinearSVC(C=0.01)
rfe = RFE(estimator=lscv, n_features_to_select=2)
rfe.fit(X,y)
print(rfe.support_)

[False  True  True False]

In [28]:
rfe.ranking_

array([3, 1, 1, 2])

In [29]:
lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X, y)
model = SelectFromModel(lsvc, prefit=True)

X_new = model.transform(X)
lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X, y)
model = SelectFromModel(lsvc, prefit=True)
X_new = model.transform(X)
X_new.shape

E:\anaconda\envs\heima\Lib\site-packages\sklearn\svm\_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
E:\anaconda\envs\heima\Lib\site-packages\sklearn\svm\_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

(150, 3)